spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
#    schema:
#    data:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect