spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doctor_on_demand
    username: postgres
    password: postgres
#    schema: classpath:db/prod/prod-schema.sql
#    data: classpath:db/prod/prod-data.sql
#    initialization-mode: always
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect